Update UA Identifier to Google Analytics 4 Measurement ID
autogluon/autogluon pull request #3278
Opened 2023-06-05 20:16 UTC by gidler

*Description of changes:*
AutoGluon embeds a Google Analytics JavaScript tracker into our website docs in order to measure visits to our website documentation. We have been using a "Universal Analytics property" which is being sunset and we must migrate to a "Google Analytics 4 property". This has already been set up through our Google Analytics account. To complete the migration, we need to replace our existing `UA ID` in our website docs with our new `GA4 ID`.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-06-05 20:28 UTC, Innixma approved these changes
LGTM, we can merge directly after v0.8 release

2023-06-05 20:29 UTC, Innixma requested changes
Marking as request changes to avoid pre-emptive merge

2023-07-21 21:49 UTC, Innixma approved these changes
@gidler are we good to merge this?

2023-10-10 17:20 UTC, closed without merging

2023-10-10 17:21 UTC, gidler commented
This change was already incorporated here: https://github.com/autogluon/autogluon/pull/3330/files