0.8.2 post release
autogluon/autogluon pull request #3552
Opened 2023-09-29 22:29 UTC by tonyhoo

*Issue #, if available:*

*Description of changes:*

Update the stable website for 0.8.2 release

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-09-29 22:33 UTC, Innixma requested changes
We actually shouldn't make these changes. The problem is not the version in stable, it is the fact that it is pointing to the wrong link.

2023-09-29 23:57 UTC, Innixma commented
Opened a PR which should fix the problem: https://github.com/autogluon/autogluon/pull/3553

2023-09-30 05:51 UTC, tonyhoo commented
@Innixma We need to update the version for stable anyway as it is still reflecting the 0.8.1 release which is outdated unless we have a reason to do so

2023-10-03 15:21 UTC, gidler commented
These look like the correct changes to me. I'm wondering if we missed [these steps](https://github.com/autogluon/autogluon/blob/master/release_instructions/ReleaseInstructions.md#post-release) during the post-release of version `0.8.2`. Maybe that means we need to make them more explicit?

2023-10-06 00:01 UTC, Innixma commented on VERSION
> +0.8.3
This should be 0.8.2 for the stable release

2023-10-06 00:01 UTC, Innixma commented on docs/conf.py
> +release = '0.8.3'
This should be 0.8.2 for the stable release

2023-10-09 23:27 UTC, Innixma approved these changes
Updated to address requested changes

2023-10-09 23:28 UTC, merged