Fix test_dump_hf
autogluon/autogluon pull request #4260
Opened 2024-06-12 23:28 UTC by suzhoum

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-06-12 23:45 UTC, yinweisu commented
| Previous CI Run | Current CI Run |
| :---: | :---: |

2024-06-13 06:14 UTC, yinweisu commented
| Previous CI Run | Current CI Run |
| :---: | :---: |

2024-06-13 07:14 UTC, yinweisu commented
| Previous CI Run | Current CI Run |
| :---: | :---: |

2024-06-13 20:06 UTC, yinweisu commented
| Previous CI Run | Current CI Run |
| :---: | :---: |

2024-06-14 21:39 UTC, Innixma requested changes

2024-06-14 21:39 UTC, Innixma commented on multimodal/src/autogluon/multimodal/utils/load.py
> +    raise FileNotFoundError(f"File {file_path} not found after {retries} retries.")
1. Please add a detailed docstring for what this does as well as type hints.

2. Why are we using print statements? Shouldn't we be using `logger`?

3. Why is this in a try/except block? If we find the file via `os.path.exists`, why are we allowing for exceptions?

4. Why would we find the file in subsequent tries if we didn't find it originally? The logic doesn't quite make sense to me.

5. Even if we succeed we are calling time.sleep. This means even if we succeed the first try we are sleeping for 2 seconds without reason.

6. If we retried all times and failed each time, we still call time.sleep before raising the exception, which is unnecessary. time.sleep should only be called if the file wasn't found and there are retries remaining.

7. How is this change related to fixing the test_dump_hf unit test?

2024-06-14 21:39 UTC, Innixma commented on multimodal/tests/unittests/others/test_dump_model.py
> +        "env.num_workers": 0,
why 0?

2024-06-14 21:39 UTC, Innixma commented on multimodal/tests/unittests/others_2/test_hpo.py
> +    )
Why are we getting rid of shutil calls?

2024-06-14 21:39 UTC, Innixma commented on multimodal/tests/unittests/others_2/test_hpo.py
> +    )
Why are we getting rid of shutil calls?

2024-06-14 21:39 UTC, Innixma commented on multimodal/tests/unittests/utils/unittest_datasets.py
> +        return "roc_auc"
why?

2024-07-31 17:56 UTC, suzhoum commented
Closing now as the other fix seems to be working.

2024-07-31 17:56 UTC, closed without merging